import * as ns from '../src/js/number-systems.js';

console.log('--- Ana dönüşümler ---');
console.log('10 -> bin:', ns.decimalToBinary(10));
console.log('10 -> oct:', ns.decimalToOctal(10));
console.log('10 -> hex:', ns.decimalToHex(10));
console.log('255 -> bin:', ns.decimalToBinary(255));
console.log('255 -> hex:', ns.decimalToHex(255));
console.log('1100 -> dec:', ns.binaryToDecimal('1100'));
console.log('17 -> dec:', ns.octalToDecimal('17'));
console.log('FF -> dec:', ns.hexToDecimal('FF'));
console.log('convert(255,16,2):', ns.convert(255, 16, 2));
console.log('--- format ---');
console.log('formatBinary(255,8):', ns.formatBinary(255, 8));
console.log('formatHex(255,2):', ns.formatHex(255, 2));
console.log('--- ASCII ---');
console.log('stringToHex A:', ns.stringToHex('A'));
console.log('stringToHex AB:', ns.stringToHex('AB'));
console.log('hexToString Hello:', ns.hexToString('48 65 6c 6c 6f'));
console.log('stringToAscii A:', ns.stringToAscii('A'));
console.log('asciiCodeToChar 65:', ns.asciiCodeToChar(65));
console.log('asciiCodeToChar 10:', ns.asciiCodeToChar(10));
console.log('generateAsciiTable 65-68:', JSON.stringify(ns.generateAsciiTable(65, 68)));
console.log('isPrintable 65:', ns.isPrintableAscii(65));
console.log('isPrintable 10:', ns.isPrintableAscii(10));
